### ISSUE TITLE
Dependency on ModelManagement

### ISSUE THREAD

**Issue by tbeu** [DLR-SR/FaultTriggering#9]
Sadly, this library relies on the encrypted Dymola library ModelManagement and therefore is neither free to use nor tool-independent.

**Comment by fvanderlinden** [comment]
The dependency on ModelManagement is removed. However, as far as I know there is no standardized method for generating FMU's and reading them. Unfortunately therefore still a dependency on Dymola exist. 
If a generalized standard is generated, this dependency can be avoided.

**Comment by tbeu** [comment]
> The dependency on ModelManagement is removed.

This holds for the FMI branch only, right?

**Comment by fvanderlinden** [comment]
I used this comment as an input to finally update all other branches. Therefore, this hold now true for all branches!

On the other hand: I have no clue on how compatible the library is with tools other than Dymola due to the heavy use of scripting to be able to generate a complete library. Unfortunately there exists no standard here.

**Comment by fvanderlinden** [comment]
Scripting is not supported for any other tool as far as I know. However the library can be used also by users of other tools without the scripting functionality. 

As the dependancy of ModelManagement is now gone, I will close this issue.

**Comment by tbeu** [comment]
FYI: ModelManagement is free of license since Dymola 2017 FD01.
